"""rate

Revision ID: 1f44305f4402
Revises: 22601d0ed435
Create Date: 2018-09-02 01:13:38.048206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f44305f4402'
down_revision = '22601d0ed435'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rate', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rate')
    # ### end Alembic commands ###
