"""empty message

Revision ID: cc1914debd60
Revises: 9bdcdb8b8a95
Create Date: 2018-07-21 16:46:49.283166

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc1914debd60'
down_revision = '9bdcdb8b8a95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tg_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_users_tg_id'), 'users', ['tg_id'], unique=True)
    op.drop_index('ix_users_telegram_id', table_name='users')
    op.drop_column('users', 'telegram_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_index('ix_users_telegram_id', 'users', ['telegram_id'], unique=True)
    op.drop_index(op.f('ix_users_tg_id'), table_name='users')
    op.drop_column('users', 'tg_id')
    # ### end Alembic commands ###
