"""educators templates

Revision ID: cc352188f8d6
Revises: cc1914debd60
Create Date: 2018-07-22 19:20:05.934546

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc352188f8d6'
down_revision = 'cc1914debd60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('educators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_educators',
    sa.Column('educator_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['educator_id'], ['educators.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('educator_id', 'user_id')
    )
    op.add_column('users', sa.Column('current_educator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'educators', ['current_educator_id'], ['id'])
    op.drop_column('users', 'educator_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('educator_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'current_educator_id')
    op.drop_table('users_educators')
    op.drop_table('educators')
    # ### end Alembic commands ###
