"""rename Lesson.places to Lessaon.locations

Revision ID: db33a5b3a3d7
Revises: cc352188f8d6
Create Date: 2018-07-29 23:09:59.382471

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'db33a5b3a3d7'
down_revision = 'cc352188f8d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('locations', sa.JSON(), nullable=True))
    op.drop_column('lessons', 'places')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('places', mysql.JSON(), nullable=True))
    op.drop_column('lessons', 'locations')
    # ### end Alembic commands ###
